baseUrl: /
handle: default
hasUrls: true
language: en-US
name: 'Emergent Method Technical Project'
primary: true
siteGroup: 77b87bdc-1ab1-46c8-bd16-8c175e49a7c1 # Emergent Method Technical Project
sortOrder: 1
